// SPDX-License-Identifier: MIT

#pragma parameter LumaBandwidth "Luma bandwidth (MHz)" 4.0 0.6 6.0 0.2
#pragma parameter ChromaBandwidth "Chroma bandwidth (MHz, each channel)" 0.8 0.6 6.0 0.2
#pragma parameter FilterType "Composite Y/C filter type (0: Notch, 1: Comb)" 1.0 0.0 1.0 1.0
#pragma parameter System "NTSC System type" 0.0 0.0 9.0 1.0
// System types: (0: Standard, 1: C64, 2: NES, 3: SMS, 4: TG16, 5: Genesis, 6: SNES, 7: Saturn, 8: PS1, 9: N64)
